name: Update Gradle Wrapper CI

on:
  workflow_dispatch:
  schedule:
    - cron: "40 14 * * 1-7"
  update-gradle-wrapper:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
